# Generated by Django 5.0.6 on 2025-05-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('subject1', models.IntegerField()),
                ('subject2', models.IntegerField()),
                ('subject3', models.IntegerField()),
                ('total', models.IntegerField(blank=True, null=True)),
                ('result_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
